// ============================================================
// SAKUGAME — Undercover word pairs
// ============================================================
// HOW IT WORKS:
//   Each entry is a pair of SIMILAR words: ["Word A", "Word B", "type"]
//   - All CIVILIANS get one word of the pair
//   - The UNDERCOVER gets the OTHER one
//   - "type" is "c" (anime characters) or "s" (anime series) — info only
//
// The game picks a random pair each round. Good pairs are things that are
// similar enough to be described with the same clues, but not identical.
//
// TIP: you usually DON'T need to edit this file! Logged-in players can add
// pairs directly from the site: Create Room → 🕵️ Undercover →
// "📝 Manage My Word Pairs" (with AniList search + pictures — saved online).
// Those custom pairs are ADDED ON TOP of the built-in list below.
//
// FEEL FREE TO EDIT ANYWAY if you prefer: add/remove pairs below, save,
// upload — that's it. Just keep the exact format: ["First", "Second", "c"],
// ============================================================

const UNDERCOVER_PAIRS = [
  // ---------- ANIME CHARACTERS ----------
  ["Naruto", "Sasuke", "c"],
  ["Goku", "Vegeta", "c"],
  ["Luffy", "Zoro", "c"],
  ["Luffy", "Ace", "c"],
  ["Sanji", "Zoro", "c"],
  ["Eren", "Mikasa", "c"],
  ["Eren", "Armin", "c"],
  ["Levi", "Erwin", "c"],
  ["Light Yagami", "L", "c"],
  ["Near", "Mello", "c"],
  ["Killua", "Gon", "c"],
  ["Kurapika", "Leorio", "c"],
  ["Hisoka", "Illumi", "c"],
  ["Saitama", "Genos", "c"],
  ["Saitama", "Garou", "c"],
  ["Deku", "Bakugo", "c"],
  ["Todoroki", "Deku", "c"],
  ["All Might", "Endeavor", "c"],
  ["Kirishima", "Bakugo", "c"],
  ["Tanjiro", "Zenitsu", "c"],
  ["Tanjiro", "Inosuke", "c"],
  ["Giyu", "Shinobu", "c"],
  ["Rengoku", "Tengen", "c"],
  ["Nezuko", "Kanao", "c"],
  ["Satoru Gojo", "Geto", "c"],
  ["Satoru Gojo", "Sukuna", "c"],
  ["Yuji", "Megumi", "c"],
  ["Yuji", "Todo", "c"],
  ["Maki", "Mai", "c"],
  ["Itachi", "Sasuke", "c"],
  ["Kakashi", "Obito", "c"],
  ["Jiraiya", "Orochimaru", "c"],
  ["Minato", "Kakashi", "c"],
  ["Edward Elric", "Alphonse Elric", "c"],
  ["Roy Mustang", "Maes Hughes", "c"],
  ["Lelouch", "Suzaku", "c"],
  ["Spike Spiegel", "Jet Black", "c"],
  ["Senku", "Taiju", "c"],
  ["Senku", "Gen", "c"],
  ["Ash Ketchum", "Gary Oak", "c"],
  ["Pikachu", "Charizard", "c"],
  ["Brock", "Misty", "c"],
  ["Rem", "Ram", "c"],
  ["Subaru", "Emilia", "c"],
  ["Kirito", "Eugeo", "c"],
  ["Asuna", "Sinon", "c"],
  ["Ichigo", "Uryu", "c"],
  ["Aizen", "Gin", "c"],
  ["Byakuya", "Renji", "c"],
  ["Natsu", "Gray", "c"],
  ["Natsu", "Gajeel", "c"],
  ["Erza", "Mirajane", "c"],
  ["Meliodas", "Ban", "c"],
  ["Meliodas", "Escanor", "c"],
  ["King", "Diane", "c"],
  ["Mob", "Reigen", "c"],
  ["Mob", "Ritsu", "c"],
  ["Denji", "Aki", "c"],
  ["Power", "Kobeni", "c"],
  ["Yor", "Loid", "c"],
  ["Thorfinn", "Askeladd", "c"],
  ["Thorfinn", "Canute", "c"],
  ["Guts", "Griffith", "c"],
  ["Frieren", "Fern", "c"],
  ["Rimuru", "Milim", "c"],
  ["Ainz", "Demiurge", "c"],
  ["Aqua", "Megumin", "c"],
  ["Ryuko", "Satsuki", "c"],
  ["Simon", "Kamina", "c"],
  ["Gintoki", "Katsura", "c"],
  ["Gintoki", "Hijikata", "c"],
  ["Miyuki Shirogane", "Ishigami", "c"],
  ["Kaguya", "Chika", "c"],
  ["Hachiman", "Yukino", "c"],
  ["Rudeus", "Paul", "c"],
  ["Tohru", "Elma", "c"],
  ["Nasa", "Tsukasa", "c"],
  ["Bocchi", "Nijika", "c"],
  ["Baki", "Yujiro", "c"],
  ["Shinra", "Arthur Boyle", "c"],
  ["Asta", "Yuno", "c"],
  ["Yami Sukehiro", "Jack the Ripper", "c"],

  // ---------- ANIME SERIES ----------
  ["Death Note", "Code Geass", "s"],
  ["Attack on Titan", "Vinland Saga", "s"],
  ["Naruto", "Bleach", "s"],
  ["One Piece", "Fairy Tail", "s"],
  ["Dragon Ball Z", "Naruto", "s"],
  ["Demon Slayer", "Jujutsu Kaisen", "s"],
  ["Hunter x Hunter", "Yu Yu Hakusho", "s"],
  ["Fire Force", "Soul Eater", "s"],
  ["Oshi no Ko", "Kaguya-sama", "s"],
  ["Sword Art Online", "Accel World", "s"],
  ["Re:Zero", "Konosuba", "s"],
  ["Overlord", "That Time I Got Reincarnated as a Slime", "s"],
  ["Steins;Gate", "Erased", "s"],
  ["Tokyo Ghoul", "Parasyte", "s"],
  ["One Punch Man", "My Hero Academia", "s"],
  ["Mob Psycho 100", "Saiki K", "s"],
  ["Chainsaw Man", "Hell's Paradise", "s"],
  ["Spy x Family", "Buddy Daddies", "s"],
  ["Your Name", "Weathering With You", "s"],
  ["A Silent Voice", "I Want to Eat Your Pancreas", "s"],
  ["Haikyuu", "Kuroko's Basketball", "s"],
  ["Blue Lock", "Ao Ashi", "s"],
  ["Cowboy Bebop", "Samurai Champloo", "s"],
  ["Evangelion", "Darling in the Franxx", "s"],
  ["Gurren Lagann", "Kill la Kill", "s"],
  ["Black Clover", "Radiant", "s"],
  ["My Hero Academia", "Assassination Classroom", "s"],
  ["Made in Abyss", "The Promised Neverland", "s"],
  ["Your Lie in April", "Anohana", "s"],
  ["Clannad", "Angel Beats", "s"],
  ["Toradora", "Golden Time", "s"],
  ["Berserk", "Claymore", "s"],
  ["Vinland Saga", "Kingdom", "s"],
  ["Dororo", "Inuyasha", "s"],
  ["Psycho-Pass", "Ghost in the Shell", "s"],
  ["Akira", "Ghost in the Shell", "s"],
  ["Monster", "Pluto", "s"],
  ["Pokémon", "Digimon", "s"],
  ["Yu-Gi-Oh!", "Cardfight Vanguard", "s"],
  ["Beyblade", "Bakugan", "s"],
  ["Bocchi the Rock", "K-On!", "s"],
  ["Solo Leveling", "The Eminence in Shadow", "s"],
  ["Tokyo Revengers", "Wind Breaker", "s"],
  ["Bungo Stray Dogs", "Moriarty the Patriot", "s"],
  ["Seven Deadly Sins", "Magi", "s"],
  ["Attack on Titan", "Kabaneri of the Iron Fortress", "s"],
  ["Frieren", "Delicious in Dungeon", "s"],
  ["Dr. Stone", "Cells at Work", "s"],
];

// ============================================================
// YOUR CUSTOM PAIRS (your list, added 2026-08-12)
// Official AniList names + pictures attached automatically.
// imgA/imgB = picture shown in-game (null = no picture available).
// Edit freely: change names, remove lines, add new ones.
// ============================================================
UNDERCOVER_PAIRS.push(
  { a: "Zuko", b: "Shouto Todoroki", type: "c", imgA: null, imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png" }, // Zuko (Avatar — not on AniList, no img)
  { a: "Yoshikage Kira", b: "Light Yagami", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b12055-eCEkIVV4qoCu.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png" }, // Yoshikage Kira / Light Yagami
  { a: "Benimaru Shinmon", b: "Genryuusai Yamamoto", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b130848-AuuIm6GR8ody.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b5726-mO7kc8Abka9J.jpg" }, // Benimaru / Yamamoto
  { a: "Kurapika", b: "Sasuke Uchiha", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png" }, // Kurapika / Sasuke
  { a: "Yuuji Itadori", b: "Sukuna", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png" }, // Yuji / Sukuna
  { a: "Beam", b: "Kisame Hoshigaki", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b157232-5GuWeqoFN9Kq.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/2672-oxbHx8n3N7WY.jpg" }, // Beam / Kisame
  { a: "Shanks", b: "Gildarts Clive", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b727-wUJx7M1z5xON.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b29502-znlVXVdXEQqg.png" }, // Shanks / Gildarts
  { a: "Kakashi Hatake", b: "Satoru Gojou", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png" }, // Kakashi / Gojo
  { a: "Subaru Natsuki", b: "Rintarou Okabe", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png" }, // Subaru / Okabe
  { a: "Puck", b: "Happy", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b90187-xJXlD84KXl3t.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b5188-1jTaic3aJ7Ds.jpg" }, // Puck (Re:Zero) / Happy
  { a: "Miyako Shikimori", b: "Akari Watanabe", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b155702-S8irhsg4QTPf.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b191672-MozVAnqyv9oZ.png" }, // Shikimori / Akari Watanabe (Fuufu Ijou)
  { a: "Iori Kitahara", b: "Kiyoshi Fujino", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b123182-tuQ2yf5IEx02.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b46557-fJ8Va6GtynPM.jpg" }, // Kitahara / Kiyoshi Fujino
  { a: "Ryou Yamada", b: "Mio Akiyama", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b264529-BvEusZnJLD2Y.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b19566-XKsMgf370b4m.png" }, // Ryo Yamada / Mio Akiyama
  { a: "Mai Sakurajima", b: "Marin Kitagawa", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png" }, // Mai / Marin
  { a: "Obito Uchiha", b: "Dabi", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b126378-RFSljq5koy5U.png" }, // Obito / Dabi
  { a: "Beerus", b: "Champa", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b76348-pGWrznfxgPIV.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/127220-yWeW7rlEJP4V.jpg" }, // Beerus / Champa
  { a: "Fern", b: "Coco", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b183965-uGFohBjlFoTp.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b129840-B2CVE0TIcKpT.png" }, // Fern / Coco
  { a: "Erza Scarlet", b: "Eris Boreas Greyrat", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b88349-5dsNUah3oBj8.png" }, // Erza / Eris
  { a: "Kiyotaka Ayanokouji", b: "Yuuichi Katagiri", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b123212-ewZgUQr9vvEM.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b122064-p5x9pgsdjj4W.jpg" }, // Ayanokoji / Yuichi
  { a: "Vanessa Enoteca", b: "Cana Alberona", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b124436-dES6CtprlZNy.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b8296-QdKicnM0gSGN.jpg" }, // Vanessa (Black Clover) / Cana (Fairy Tail)
  { a: "Itachi Uchiha", b: "Madara Uchiha", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png" }, // Itachi / Madara
  { a: "Muzan Kibutsuji", b: "Imu", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg", imgB: null }, // Muzan / Imu (no img on AniList)
  { a: "Guy Might", b: "Touji Fushiguro", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b307-xieUEdhdTVwQ.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b162722-btzdghBizxKS.jpg" }, // Gai Maito / Toji
  { a: "Cell", b: "Meruem", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/3908.jpg", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b23277-EYmIxzL64Mji.png" }, // Cell / Meruem
  { a: "Arataka Reigen", b: "Kamina", type: "c", imgA: "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png", imgB: "https://s4.anilist.co/file/anilistcdn/character/large/b2075-sWb5Xz76JWdX.png" }, // Reigen / Kamina
  { a: "Vegeto", b: "Gogeta", type: "c", imgA: null, imgB: null }, // Vegeto / Gogeta (no img on AniList)
);

// ============================================================
// Auto-generated AniList image URLs for the word lists above.
// Key = the word in lowercase. Value = official AniList picture
// (null = AniList has no entry for it — the word just shows as text).
// You should NOT need to edit this by hand.
// ============================================================
const UNDERCOVER_IMAGES = {
  "a silent voice": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20954-sYRfE5jQRtSB.jpg",
  "accel world": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11759-o3ZRpFYnP5Lc.jpg",
  "ace": "https://s4.anilist.co/file/anilistcdn/character/large/b2072-Lc6jEdsueJUK.jpg",
  "ainz": "https://s4.anilist.co/file/anilistcdn/character/large/b89103-ZsnA0r77GHsR.png",
  "aizen": "https://s4.anilist.co/file/anilistcdn/character/large/b1086-qR9218BjZTC0.png",
  "akari watanabe": "https://s4.anilist.co/file/anilistcdn/character/large/b191672-MozVAnqyv9oZ.png",
  "aki": "https://s4.anilist.co/file/anilistcdn/character/large/b137081-TSrUR3mUJL6r.png",
  "akira": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx47-4CR68arv452h.jpg",
  "all might": "https://s4.anilist.co/file/anilistcdn/character/large/b89224-K6KEuQAuYKzq.jpg",
  "alphonse elric": "https://s4.anilist.co/file/anilistcdn/character/large/b12-tCKu8yK5kFL5.jpg",
  "angel beats": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx6547-SYexAn5aFyss.png",
  "anohana": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx9989-hImMg6kCMm6I.jpg",
  "ao ashi": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx134732-OXKSrOhF9pCM.jpg",
  "aqua": "https://s4.anilist.co/file/anilistcdn/character/large/b89362-ibkc0eoECaW1.png",
  "arataka reigen": "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png",
  "armin": "https://s4.anilist.co/file/anilistcdn/character/large/b46494-g7xYYuBtYPnO.png",
  "arthur boyle": "https://s4.anilist.co/file/anilistcdn/character/large/n130715-IYNBAHBQa14y.png",
  "ash ketchum": "https://s4.anilist.co/file/anilistcdn/character/large/b2473-JDoo3I82Km4l.png",
  "askeladd": "https://s4.anilist.co/file/anilistcdn/character/large/b13020-ZdiYlNmpRUNS.png",
  "assassination classroom": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20755-dWrhs569YGUO.jpg",
  "asta": "https://s4.anilist.co/file/anilistcdn/character/large/b123285-tKijiuQErDS0.png",
  "asuna": "https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png",
  "attack on titan": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx16498-buvcRTBx4NSm.jpg",
  "baki": "https://s4.anilist.co/file/anilistcdn/character/large/b10498-Ep1aY2liGmIA.png",
  "bakugan": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx2156-z3AqxkRNfxov.png",
  "bakugo": "https://s4.anilist.co/file/anilistcdn/character/large/b88892-bdOha3lNcaN6.png",
  "ban": "https://s4.anilist.co/file/anilistcdn/character/large/b77605-NrjhQwZwgJ3l.png",
  "beam": "https://s4.anilist.co/file/anilistcdn/character/large/b157232-5GuWeqoFN9Kq.jpg",
  "beerus": "https://s4.anilist.co/file/anilistcdn/character/large/b76348-pGWrznfxgPIV.png",
  "benimaru shinmon": "https://s4.anilist.co/file/anilistcdn/character/large/b130848-AuuIm6GR8ody.jpg",
  "berserk": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx33-PSwfE5B0gejI.jpg",
  "beyblade": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b288-QLBdXz8n34yP.png",
  "black clover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx97940-fyh8o7gNbha0.png",
  "bleach": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx269-d2GmRkJbMopq.png",
  "blue lock": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx137822-U8naszP96vzC.png",
  "bocchi": "https://s4.anilist.co/file/anilistcdn/character/large/b257562-Ru35NYPfsqhY.png",
  "bocchi the rock": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx130003-HTDmeL4RGeJ4.png",
  "brock": "https://s4.anilist.co/file/anilistcdn/character/large/b3854-qMVUF2YmWYoW.png",
  "buddy daddies": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx155907-wY1RqFUHvZ60.jpg",
  "bungo stray dogs": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21311-hAXyT8Yoh6G9.jpg",
  "byakuya": "https://s4.anilist.co/file/anilistcdn/character/large/b907-kgnDKeMtEN5y.png",
  "canute": "https://s4.anilist.co/file/anilistcdn/character/large/b17438-NwyOSMxycmck.png",
  "cardfight vanguard": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx9539-g9UtWqT6iotq.png",
  "cell": "https://s4.anilist.co/file/anilistcdn/character/large/3908.jpg",
  "cells at work": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx100977-nH1J2dR7GGAk.jpg",
  "chainsaw man": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx127230-DdP4vAdssLoz.png",
  "champa": "https://s4.anilist.co/file/anilistcdn/character/large/127220-yWeW7rlEJP4V.jpg",
  "charizard": "https://s4.anilist.co/file/anilistcdn/character/large/b180037-u3b2oiaWdfAm.png",
  "chika": "https://s4.anilist.co/file/anilistcdn/character/large/b121103-UGLxT8utLPnq.png",
  "clannad": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx2167-pSDBcyc0vjej.jpg",
  "claymore": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1818-KieLJv0qo3mO.jpg",
  "coco": "https://s4.anilist.co/file/anilistcdn/character/large/b129840-B2CVE0TIcKpT.png",
  "code geass": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1575-hsmWM2ydNm1m.jpg",
  "cowboy bebop": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1-GCsPm7waJ4kS.png",
  "dabi": "https://s4.anilist.co/file/anilistcdn/character/large/b126378-RFSljq5koy5U.png",
  "darling in the franxx": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx99423-8MBxtwCeHf8B.png",
  "death note": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1535-kUgkcrfOrkUM.jpg",
  "deku": "https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png",
  "delicious in dungeon": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx153518-IVXPDY5ph3kO.jpg",
  "demiurge": "https://s4.anilist.co/file/anilistcdn/character/large/b89125-pnLki4r5UyV5.png",
  "demon slayer": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101922-WBsBl0ClmgYL.jpg",
  "denji": "https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png",
  "diane": "https://s4.anilist.co/file/anilistcdn/character/large/b74653-XpMcsLVZBnkZ.jpg",
  "digimon": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx552-zad0ts5hylQJ.jpg",
  "dororo": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101347-TGaDwEYqLfm1.jpg",
  "dr. stone": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx105333-GybuoSoOZfpH.jpg",
  "dragon ball z": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx813-ZhnFNOeCU5dQ.png",
  "edward elric": "https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg",
  "elma": "https://s4.anilist.co/file/anilistcdn/character/large/b120977-x50lrAuIAsHE.png",
  "emilia": "https://s4.anilist.co/file/anilistcdn/character/large/b88572-IzTwXEHSobRs.jpg",
  "endeavor": "https://s4.anilist.co/file/anilistcdn/character/large/b126158-Wix9rh7unTDQ.png",
  "erased": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21234-XmqW39aQ9o7O.jpg",
  "eren": "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
  "eris boreas greyrat": "https://s4.anilist.co/file/anilistcdn/character/large/b88349-5dsNUah3oBj8.png",
  "erwin": "https://s4.anilist.co/file/anilistcdn/character/large/b46496-Mu86MENd5wNB.png",
  "erza": "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg",
  "erza scarlet": "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg",
  "escanor": "https://s4.anilist.co/file/anilistcdn/character/large/b90202-1H7FIX2hDmYd.png",
  "eugeo": "https://s4.anilist.co/file/anilistcdn/character/large/b70899-TwMq5mtH5ifc.jpg",
  "evangelion": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx30-AI1zr74Dh4ye.jpg",
  "fairy tail": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b6702-KI4qgSMyI8Pm.png",
  "fern": "https://s4.anilist.co/file/anilistcdn/character/large/b183965-uGFohBjlFoTp.png",
  "fire force": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx105310-2PKUvoaA6fTn.jpg",
  "frieren": "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png",
  "frieren|s": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx154587-qQTzQnEJJ3oB.jpg",
  "gajeel": "https://s4.anilist.co/file/anilistcdn/character/large/b16893-l9HhHQ8j09H5.jpg",
  "garou": "https://s4.anilist.co/file/anilistcdn/character/large/b89277-xBGb4B5YISXg.png",
  "gary oak": "https://s4.anilist.co/file/anilistcdn/character/large/b4848-vR9au1dEKjyy.png",
  "gen": "https://s4.anilist.co/file/anilistcdn/character/large/b127445-oUCyS7Tl8l5D.png",
  "genos": "https://s4.anilist.co/file/anilistcdn/character/large/b73979-tVi9maPID881.jpg",
  "genryuusai yamamoto": "https://s4.anilist.co/file/anilistcdn/character/large/b5726-mO7kc8Abka9J.jpg",
  "geto": "https://s4.anilist.co/file/anilistcdn/character/large/b133699-FCnXaISgazAi.png",
  "ghost in the shell": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx43-Y6EjeEMM14dj.png",
  "gildarts clive": "https://s4.anilist.co/file/anilistcdn/character/large/b29502-znlVXVdXEQqg.png",
  "gin": "https://s4.anilist.co/file/anilistcdn/character/large/b1087-wMTny26FezYB.png",
  "gintoki": "https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png",
  "giyu": "https://s4.anilist.co/file/anilistcdn/character/large/b130050-qsLThJs5VIbz.png",
  "gogeta": null,
  "goku": "https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png",
  "golden time": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx17895-M8yjOyMxHf5X.jpg",
  "gon": "https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg",
  "gray": "https://s4.anilist.co/file/anilistcdn/character/large/b4839-p2SBgjdTxHxk.png",
  "griffith": "https://s4.anilist.co/file/anilistcdn/character/large/b424-Jfrsf8I7zBps.png",
  "gurren lagann": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx2001-XwRnjzGeFWRQ.png",
  "guts": "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png",
  "guy might": "https://s4.anilist.co/file/anilistcdn/character/large/b307-xieUEdhdTVwQ.png",
  "hachiman": "https://s4.anilist.co/file/anilistcdn/character/large/b67065-Dhec6tE2yWA9.png",
  "haikyuu": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20464-ooZUyBe4ptp9.png",
  "happy": "https://s4.anilist.co/file/anilistcdn/character/large/b5188-1jTaic3aJ7Ds.jpg",
  "hell's paradise": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx128893-Gc2t8b8M0mVu.jpg",
  "hijikata": "https://s4.anilist.co/file/anilistcdn/character/large/b2650-zgkj5l8mIOnn.png",
  "hisoka": "https://s4.anilist.co/file/anilistcdn/character/large/b31-FZckOuu7L1un.png",
  "hunter x hunter": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11061-y5gsT1hoHuHw.png",
  "i want to eat your pancreas": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx99750-pNyly9d3MEgV.jpg",
  "ichigo": "https://s4.anilist.co/file/anilistcdn/character/large/b124382-bSBkjtYjJQtr.png",
  "illumi": "https://s4.anilist.co/file/anilistcdn/character/large/b57-pTFguojSOQZW.png",
  "imu": null,
  "inosuke": "https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg",
  "inuyasha": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx249-jVBkyLnBvnRE.png",
  "iori kitahara": "https://s4.anilist.co/file/anilistcdn/character/large/b123182-tuQ2yf5IEx02.jpg",
  "ishigami": "https://s4.anilist.co/file/anilistcdn/character/large/b124142-XUO1g7wRqkaT.png",
  "itachi": "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
  "itachi uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
  "jack the ripper": "https://s4.anilist.co/file/anilistcdn/character/large/b124456-llrSWfAXlnbb.png",
  "jet black": "https://s4.anilist.co/file/anilistcdn/character/large/b3-JjH9Si9UM1NZ.png",
  "jiraiya": "https://s4.anilist.co/file/anilistcdn/character/large/b2423-RO5MyoXSA9OL.png",
  "jujutsu kaisen": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx113415-LHBAeoZDIsnF.jpg",
  "k-on!": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx5680-r3AI3Cwfv0Aq.png",
  "kabaneri of the iron fortress": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21196-2PfPfIDrxKki.jpg",
  "kaguya": "https://s4.anilist.co/file/anilistcdn/character/large/b120649-NPaWaIpWy60E.png",
  "kaguya-sama": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101921-ufrjLzhSz7L1.jpg",
  "kakashi": "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
  "kakashi hatake": "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
  "kamina": "https://s4.anilist.co/file/anilistcdn/character/large/b2075-sWb5Xz76JWdX.png",
  "cana alberona": "https://s4.anilist.co/file/anilistcdn/character/large/b8296-QdKicnM0gSGN.jpg",
  "kanao": "https://s4.anilist.co/file/anilistcdn/character/large/b139038-OcOoDUyLEsRn.png",
  "katsura": "https://s4.anilist.co/file/anilistcdn/character/large/b1533-tSqUrj2DOK5p.png",
  "kill la kill": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b18679-lbkq7iYESoFW.png",
  "killua": "https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg",
  "king": "https://s4.anilist.co/file/anilistcdn/character/large/b83801-52RnDXQDZ1I7.png",
  "kingdom": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx12031-1nVQa5nXPt48.png",
  "kirishima": "https://s4.anilist.co/file/anilistcdn/character/large/b87277-oUaqrI1iBzu6.png",
  "kirito": "https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png",
  "kisame hoshigaki": "https://s4.anilist.co/file/anilistcdn/character/large/2672-oxbHx8n3N7WY.jpg",
  "kiyoshi fujino": "https://s4.anilist.co/file/anilistcdn/character/large/b46557-fJ8Va6GtynPM.jpg",
  "kiyotaka ayanokouji": "https://s4.anilist.co/file/anilistcdn/character/large/b123212-ewZgUQr9vvEM.png",
  "kobeni": "https://s4.anilist.co/file/anilistcdn/character/large/b144594-0dbO1NSYeZ12.png",
  "konosuba": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21202-mPOr80AEjUcZ.png",
  "kurapika": "https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png",
  "kuroko's basketball": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11771-uvr44RAwRxPw.jpg",
  "l": "https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png",
  "lelouch": "https://s4.anilist.co/file/anilistcdn/character/large/b417-gVLmIJu9phcK.png",
  "leorio": "https://s4.anilist.co/file/anilistcdn/character/large/b29-RgzoSeKmDYzl.jpg",
  "levi": "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png",
  "light yagami": "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
  "loid": "https://s4.anilist.co/file/anilistcdn/character/large/b138101-7NCB0Md8zA6G.png",
  "luffy": "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
  "madara uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png",
  "made in abyss": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx97986-TQ7dCgbS3y5s.jpg",
  "maes hughes": "https://s4.anilist.co/file/anilistcdn/character/large/b69-MRetSG8Qevvu.png",
  "magi": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx14513-HuUdrFFYftA7.jpg",
  "mai": "https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png",
  "mai sakurajima": "https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png",
  "maki": "https://s4.anilist.co/file/anilistcdn/character/large/b134167-5TCytk45YByD.png",
  "marin kitagawa": "https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png",
  "megumi": "https://s4.anilist.co/file/anilistcdn/character/large/b126635-L0y3I92JSUkN.png",
  "megumin": "https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png",
  "meliodas": "https://s4.anilist.co/file/anilistcdn/character/large/b72921-XDHNd1wflN6P.png",
  "mello": "https://s4.anilist.co/file/anilistcdn/character/large/b463-QBLeLf6XxVg6.png",
  "meruem": "https://s4.anilist.co/file/anilistcdn/character/large/b23277-EYmIxzL64Mji.png",
  "mikasa": "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
  "milim": "https://s4.anilist.co/file/anilistcdn/character/large/b128036-lW0dxNwerqw4.png",
  "minato": "https://s4.anilist.co/file/anilistcdn/character/large/b2535-Xq9WKNPJQEt3.png",
  "mio akiyama": "https://s4.anilist.co/file/anilistcdn/character/large/b19566-XKsMgf370b4m.png",
  "mirajane": "https://s4.anilist.co/file/anilistcdn/character/large/b5190-Xql1rGKUv1ql.png",
  "misty": "https://s4.anilist.co/file/anilistcdn/character/large/b2909-wNDR5aaxwDdi.png",
  "miyako shikimori": "https://s4.anilist.co/file/anilistcdn/character/large/b155702-S8irhsg4QTPf.png",
  "miyuki shirogane": "https://s4.anilist.co/file/anilistcdn/character/large/b121101-Q8HzKP15At2d.png",
  "mob": "https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png",
  "mob psycho 100": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21507-6YUSbh2m0N1p.jpg",
  "monster": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx19-gtMC64182sm4.jpg",
  "moriarty the patriot": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx114124-def92qPuIVeK.jpg",
  "muzan kibutsuji": "https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg",
  "my hero academia": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21459-nYh85uj2Fuwr.jpg",
  "naruto": "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png",
  "naruto|s": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20-dE6UHbFFg1A5.jpg",
  "nasa": "https://s4.anilist.co/file/anilistcdn/character/large/b130944-Bi9EfjnNO3LT.png",
  "natsu": "https://s4.anilist.co/file/anilistcdn/character/large/b5187-y1OEdRu9sPN2.png",
  "near": "https://s4.anilist.co/file/anilistcdn/character/large/n464-6KeJpU6g7Hwj.jpg",
  "nezuko": "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png",
  "nijika": "https://s4.anilist.co/file/anilistcdn/character/large/b261674-a8tJYvtzqWgC.png",
  "obito": "https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png",
  "obito uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png",
  "one piece": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21-ELSYx3yMPcKM.jpg",
  "one punch man": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21087-B5DHjqZ3kW4b.jpg",
  "orochimaru": "https://s4.anilist.co/file/anilistcdn/character/large/n2455-V9tLMS3TIgJW.png",
  "oshi no ko": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx150672-WqmmwZ4nMzAy.png",
  "overlord": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20832-vUNm5zrYWifc.jpg",
  "parasyte": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20623-dUARfggnNDOe.jpg",
  "paul": "https://s4.anilist.co/file/anilistcdn/character/large/b88347-YtQTlChhN50m.png",
  "pikachu": "https://s4.anilist.co/file/anilistcdn/character/large/b3891-edgrZOgCJ9do.jpg",
  "pluto": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx99088-LTJskMD1wbbQ.png",
  "pokémon": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b527-t6dBVJ5OVcXK.png",
  "power": "https://s4.anilist.co/file/anilistcdn/character/large/b137079-6yLEUYR3bmpr.png",
  "psycho-pass": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx13601-i42VFuHpqEOJ.jpg",
  "puck": "https://s4.anilist.co/file/anilistcdn/character/large/b5060-PWn2hc2nBy9J.jpg",
  "radiant": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx101024-4dFUVMKSE0Q1.jpg",
  "ram": "https://s4.anilist.co/file/anilistcdn/character/large/b88576-NWkotUiJ3mK3.png",
  "re:zero": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21355-wRVUrGxpvIQQ.jpg",
  "reigen": "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png",
  "rem": "https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png",
  "rengoku": "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png",
  "renji": "https://s4.anilist.co/file/anilistcdn/character/large/b906-ImRjx5HFM8X6.png",
  "rimuru": "https://s4.anilist.co/file/anilistcdn/character/large/b123962-eL9yGV0NLMF7.png",
  "rintarou okabe": "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png",
  "ritsu": "https://s4.anilist.co/file/anilistcdn/character/large/b89618-iSTUyCdu1yZ8.png",
  "roy mustang": "https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png",
  "rudeus": "https://s4.anilist.co/file/anilistcdn/character/large/b88348-bIe5XnXdRpmX.png",
  "ryou yamada": "https://s4.anilist.co/file/anilistcdn/character/large/b264529-BvEusZnJLD2Y.png",
  "ryuko": "https://s4.anilist.co/file/anilistcdn/character/large/b83797-ix0Cl5OMfV22.png",
  "saiki k": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21804-As6tDLAvEvNY.jpg",
  "saitama": "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg",
  "samurai champloo": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx205-7tHVFu6dPBm9.png",
  "sanji": "https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png",
  "sasuke": "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
  "sasuke uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
  "satoru gojo": "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
  "satoru gojou": "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
  "satsuki": "https://s4.anilist.co/file/anilistcdn/character/large/b83799-oPxSwMA9XAvu.png",
  "senku": "https://s4.anilist.co/file/anilistcdn/character/large/b124142-XUO1g7wRqkaT.png",
  "seven deadly sins": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20789-Ma5ouSYPkru9.jpg",
  "shanks": "https://s4.anilist.co/file/anilistcdn/character/large/b727-wUJx7M1z5xON.png",
  "shinobu": "https://s4.anilist.co/file/anilistcdn/character/large/b23602-Z4MDNYcoAWZu.png",
  "shinra": "https://s4.anilist.co/file/anilistcdn/character/large/n120462-oSWdz2MhkbDE.png",
  "shouto todoroki": "https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png",
  "simon": "https://s4.anilist.co/file/anilistcdn/character/large/b2257-jnalsdnIX1vN.jpg",
  "sinon": "https://s4.anilist.co/file/anilistcdn/character/large/b55147-1fCU8lONEuZQ.png",
  "solo leveling": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx151807-it355ZgzquUd.png",
  "soul eater": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx3588-fSMggQoFSbUI.png",
  "spike spiegel": "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png",
  "spy x family": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx140960-Kb6R5nYQfjmP.jpg",
  "steins;gate": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx9253-tIUXF2gfU8Sg.jpg",
  "subaru": "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png",
  "subaru natsuki": "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png",
  "sukuna": "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png",
  "suzaku": "https://s4.anilist.co/file/anilistcdn/character/large/b559-KRvTdc6zdCuU.jpg",
  "sword art online": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11757-SxYDUzdr9rh2.jpg",
  "taiju": "https://s4.anilist.co/file/anilistcdn/character/large/b124146-TeXd4r0upuIX.jpg",
  "tanjiro": "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png",
  "tengen": "https://s4.anilist.co/file/anilistcdn/character/large/b136071-99Kexnnn2PiV.png",
  "that time i got reincarnated as a slime": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101280-tDxCVJm714nt.jpg",
  "the eminence in shadow": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx130298-YMdcKHytpWNH.jpg",
  "the promised neverland": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101759-8UR7r9MNVpz2.jpg",
  "thorfinn": "https://s4.anilist.co/file/anilistcdn/character/large/b10138-zOPrka0ddZOR.png",
  "todo": "https://s4.anilist.co/file/anilistcdn/character/large/b137975-6TH7PiLWJaqy.png",
  "todoroki": "https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png",
  "tohru": "https://s4.anilist.co/file/anilistcdn/character/large/b120970-knjWLdlQIs1y.jpg",
  "tokyo ghoul": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b20605-k665mVkSug8D.jpg",
  "tokyo revengers": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx120120-cWDmnmeEntSe.jpg",
  "toradora": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx4224-PXVMBLNwy2aF.jpg",
  "touji fushiguro": "https://s4.anilist.co/file/anilistcdn/character/large/b162722-btzdghBizxKS.jpg",
  "tsukasa": "https://s4.anilist.co/file/anilistcdn/character/large/b131106-ZJOpYOpurcYS.png",
  "uryu": "https://s4.anilist.co/file/anilistcdn/character/large/b564-a6LJitrjSfKC.jpg",
  "vanessa enoteca": "https://s4.anilist.co/file/anilistcdn/character/large/b124436-dES6CtprlZNy.png",
  "vegeta": "https://s4.anilist.co/file/anilistcdn/character/large/b913-NIFkKazWM8VO.png",
  "vegeto": null,
  "vinland saga": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101348-2fhDFPCuMNiz.jpg",
  "weathering with you": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx106286-5COcpd0J9VbL.png",
  "wind breaker": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx163270-wboZJp0ybwVK.jpg",
  "yami sukehiro": "https://s4.anilist.co/file/anilistcdn/character/large/b124440-Lpdo6y8cljV6.png",
  "yor": "https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png",
  "yoshikage kira": "https://s4.anilist.co/file/anilistcdn/character/large/b12055-eCEkIVV4qoCu.png",
  "your lie in april": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20665-TLgkL8T8IRFd.png",
  "your name": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21519-SUo3ZQuCbYhJ.png",
  "yu yu hakusho": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx392-z90299zIvYmx.png",
  "yu-gi-oh!": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx481-Qpqy1TQBOxZO.png",
  "yuji": "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png",
  "yujiro": "https://s4.anilist.co/file/anilistcdn/character/large/b10499-yqTyqgrkbZfO.jpg",
  "yukino": "https://s4.anilist.co/file/anilistcdn/character/large/b67067-gqhgjlni0Bcf.png",
  "yuno": "https://s4.anilist.co/file/anilistcdn/character/large/b123284-w6kIFYnTclMd.png",
  "yuuichi katagiri": "https://s4.anilist.co/file/anilistcdn/character/large/b122064-p5x9pgsdjj4W.jpg",
  "yuuji itadori": "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png",
  "zenitsu": "https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png",
  "zoro": "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
  "zuko": null,
};
