// ============================================================
// SAKUGAME — Undercover word pairs
// ============================================================
// HOW IT WORKS:
//   Each entry is a pair of SIMILAR words: ["Word A", "Word B", "type"]
//   - All CIVILIANS get one word of the pair
//   - The UNDERCOVER gets the OTHER one
//   - "type" is "c" (anime characters) or "s" (anime series) — info only
//
// The game picks a random pair each round. Good pairs are things that are
// similar enough to be described with the same clues, but not identical.
//
// TIP: you usually DON'T need to edit this file! Logged-in players can add
// pairs directly from the site: Create Room → 🕵️ Undercover →
// "📝 Manage My Word Pairs" (with AniList search + pictures — saved online).
// Those custom pairs are ADDED ON TOP of the built-in list below.
//
// FEEL FREE TO EDIT ANYWAY if you prefer: add/remove pairs below, save,
// upload — that's it. Just keep the exact format: ["First", "Second", "c"],
// ============================================================

const UNDERCOVER_PAIRS = [
  // ---------- ANIME CHARACTERS ----------
  ["Naruto", "Sasuke", "c"],
  ["Goku", "Vegeta", "c"],
  ["Luffy", "Zoro", "c"],
  ["Luffy", "Ace", "c"],
  ["Sanji", "Zoro", "c"],
  ["Eren", "Mikasa", "c"],
  ["Eren", "Armin", "c"],
  ["Levi", "Erwin", "c"],
  ["Light Yagami", "L", "c"],
  ["Near", "Mello", "c"],
  ["Killua", "Gon", "c"],
  ["Kurapika", "Leorio", "c"],
  ["Hisoka", "Illumi", "c"],
  ["Saitama", "Genos", "c"],
  ["Saitama", "Garou", "c"],
  ["Deku", "Bakugo", "c"],
  ["Todoroki", "Deku", "c"],
  ["All Might", "Endeavor", "c"],
  ["Kirishima", "Bakugo", "c"],
  ["Tanjiro", "Zenitsu", "c"],
  ["Tanjiro", "Inosuke", "c"],
  ["Giyu", "Shinobu", "c"],
  ["Rengoku", "Tengen", "c"],
  ["Nezuko", "Kanao", "c"],
  ["Satoru Gojo", "Geto", "c"],
  ["Satoru Gojo", "Sukuna", "c"],
  ["Yuji", "Megumi", "c"],
  ["Yuji", "Todo", "c"],
  ["Maki", "Mai", "c"],
  ["Itachi", "Sasuke", "c"],
  ["Kakashi", "Obito", "c"],
  ["Jiraiya", "Orochimaru", "c"],
  ["Minato", "Kakashi", "c"],
  ["Edward Elric", "Alphonse Elric", "c"],
  ["Roy Mustang", "Maes Hughes", "c"],
  ["Lelouch", "Suzaku", "c"],
  ["Spike Spiegel", "Jet Black", "c"],
  ["Senku", "Taiju", "c"],
  ["Senku", "Gen", "c"],
  ["Ash Ketchum", "Gary Oak", "c"],
  ["Pikachu", "Charizard", "c"],
  ["Brock", "Misty", "c"],
  ["Rem", "Ram", "c"],
  ["Subaru", "Emilia", "c"],
  ["Kirito", "Eugeo", "c"],
  ["Asuna", "Sinon", "c"],
  ["Ichigo", "Uryu", "c"],
  ["Aizen", "Gin", "c"],
  ["Byakuya", "Renji", "c"],
  ["Natsu", "Gray", "c"],
  ["Natsu", "Gajeel", "c"],
  ["Erza", "Mirajane", "c"],
  ["Meliodas", "Ban", "c"],
  ["Meliodas", "Escanor", "c"],
  ["King", "Diane", "c"],
  ["Mob", "Reigen", "c"],
  ["Mob", "Ritsu", "c"],
  ["Denji", "Aki", "c"],
  ["Power", "Kobeni", "c"],
  ["Yor", "Loid", "c"],
  ["Thorfinn", "Askeladd", "c"],
  ["Thorfinn", "Canute", "c"],
  ["Guts", "Griffith", "c"],
  ["Frieren", "Fern", "c"],
  ["Rimuru", "Milim", "c"],
  ["Ainz", "Demiurge", "c"],
  ["Aqua", "Megumin", "c"],
  ["Ryuko", "Satsuki", "c"],
  ["Simon", "Kamina", "c"],
  ["Gintoki", "Katsura", "c"],
  ["Gintoki", "Hijikata", "c"],
  ["Miyuki Shirogane", "Ishigami", "c"],
  ["Kaguya", "Chika", "c"],
  ["Hachiman", "Yukino", "c"],
  ["Rudeus", "Paul", "c"],
  ["Tohru", "Elma", "c"],
  ["Nasa", "Tsukasa", "c"],
  ["Bocchi", "Nijika", "c"],
  ["Baki", "Yujiro", "c"],
  ["Shinra", "Arthur Boyle", "c"],
  ["Asta", "Yuno", "c"],
  ["Yami Sukehiro", "Jack the Ripper", "c"],

  // ---------- ANIME SERIES ----------
  ["Death Note", "Code Geass", "s"],
  ["Attack on Titan", "Vinland Saga", "s"],
  ["Naruto", "Bleach", "s"],
  ["One Piece", "Fairy Tail", "s"],
  ["Dragon Ball Z", "Naruto", "s"],
  ["Demon Slayer", "Jujutsu Kaisen", "s"],
  ["Hunter x Hunter", "Yu Yu Hakusho", "s"],
  ["Fire Force", "Soul Eater", "s"],
  ["Oshi no Ko", "Kaguya-sama", "s"],
  ["Sword Art Online", "Accel World", "s"],
  ["Re:Zero", "Konosuba", "s"],
  ["Overlord", "That Time I Got Reincarnated as a Slime", "s"],
  ["Steins;Gate", "Erased", "s"],
  ["Tokyo Ghoul", "Parasyte", "s"],
  ["One Punch Man", "My Hero Academia", "s"],
  ["Mob Psycho 100", "Saiki K", "s"],
  ["Chainsaw Man", "Hell's Paradise", "s"],
  ["Spy x Family", "Buddy Daddies", "s"],
  ["Your Name", "Weathering With You", "s"],
  ["A Silent Voice", "I Want to Eat Your Pancreas", "s"],
  ["Haikyuu", "Kuroko's Basketball", "s"],
  ["Blue Lock", "Ao Ashi", "s"],
  ["Cowboy Bebop", "Samurai Champloo", "s"],
  ["Evangelion", "Darling in the Franxx", "s"],
  ["Gurren Lagann", "Kill la Kill", "s"],
  ["Black Clover", "Radiant", "s"],
  ["My Hero Academia", "Assassination Classroom", "s"],
  ["Made in Abyss", "The Promised Neverland", "s"],
  ["Your Lie in April", "Anohana", "s"],
  ["Clannad", "Angel Beats", "s"],
  ["Toradora", "Golden Time", "s"],
  ["Berserk", "Claymore", "s"],
  ["Vinland Saga", "Kingdom", "s"],
  ["Dororo", "Inuyasha", "s"],
  ["Psycho-Pass", "Ghost in the Shell", "s"],
  ["Akira", "Ghost in the Shell", "s"],
  ["Monster", "Pluto", "s"],
  ["Pokémon", "Digimon", "s"],
  ["Yu-Gi-Oh!", "Cardfight Vanguard", "s"],
  ["Beyblade", "Bakugan", "s"],
  ["Bocchi the Rock", "K-On!", "s"],
  ["Solo Leveling", "The Eminence in Shadow", "s"],
  ["Tokyo Revengers", "Wind Breaker", "s"],
  ["Bungo Stray Dogs", "Moriarty the Patriot", "s"],
  ["Seven Deadly Sins", "Magi", "s"],
  ["Attack on Titan", "Kabaneri of the Iron Fortress", "s"],
  ["Frieren", "Delicious in Dungeon", "s"],
  ["Dr. Stone", "Cells at Work", "s"],
];
